title: Jon Dickerson - Data Scientist
email: jonathan.d.dickerson@gmail.com
description: Portfolio of analysis for Jon Dickerson. Work in progress. 
url: 'http://www.jondickerson.com'
github_username: jaydik

markdown: kramdown
