title: Jon Dickerson - Data Scientist
title_short: Jon Dickerson
email: jonathan.d.dickerson@gmail.com
phone: 201.375.1827
description: Portfolio of analysis for Jon Dickerson.
url: 'http://www.jondickerson.com'
github_username: jaydik
linkedin_username: jondickerson1
kaggle_username: jaydik

markdown: kramdown
